@startuml シーケンス図(起動時)

actor User as user
participant main.py as Main
participant App
participant CustomCTk
participant MyModel
participant Page1Controller
participant Page2Controller
participant Page1

== アプリケーション起動 ==
user -> Main : 実行
Main -> App : インスタンス生成
App -> CustomCTk : インスタンス生成\nテーマカラーやウィンドウサイズ設定
App -> MyModel : インスタンス生成\nデータ保持
App -> Page1Controller : インスタンス生成(root, my_model)
Page1Controller -> CustomCTk : set_page(Page1, controller)\n※CustomCTkの管理コントローラとして保持
App -> Page2Controller : インスタンス生成(root, my_model)
Page2Controller -> CustomCTk : set_page(Page2, controller)\n※CustomCTkの管理コントローラとして保持

== 最初のページを表示 ==
App -> Page1Controller : show()\nページ表示処理
Page1Controller -> Page1Controller : _send_view_data()\nページ表示データ取得
Page1Controller -> Page1 : インスタンス生成(master, controller, data)\nUI生成

== メインループ開始 ==
App -> CustomCTk : mainloop()
CustomCTk -> user : 画面表示

@enduml
