@startuml ページ遷移

actor User as user
participant Page1
participant Page1Controller
participant CustomCTk
participant Page2Controller
participant Page2

== ユーザー操作 ==
user -> Page1 : "Send"ボタンをクリック

== コントローラによる処理 ==
Page1 -> Page1Controller : goto_page("Page2")\nページ遷移処理呼び出し
Page1Controller -> CustomCTk : show_page("Page2")\n"Page2"のコントローラ取得
CustomCTk -> Page2Controller : show()\nPage2表示処理
Page2Controller -> Page2Controller : _send_view_data()\n表示用データ取得

== ページ2の表示 ==
Page2Controller -> Page2 : インスタンス生成(master, controller, data)\nUI生成
Page2 -> user : ページ2が表示される

@enduml
